//
//  SCFilterCodeGenerator.m
//  CoreImageShop
//
//  Created by Simon CORSIN on 19/05/14.
//
//

#import "SCFilterCodeGenerator.h"
#import <SCRecorderMac/SCRecorderMac.h>
#import "SCFilterParameterConverterManager.h"

@implementation SCFilterCodeGenerator

- (void)appendHeader:(NSMutableString *)code {
    [code appendString:@"//\n"];
    [code appendString:@"// Code Generated by CoreImageShop\n"];
    [code appendString:@"//\n\n"];
}

- (NSString *)generateHeader:(NSString *)filterName {
    NSMutableString *code = [NSMutableString new];
    
    [self appendHeader:code];
    
    switch (self.outputSystem) {
        case FilterCodeGeneratorOutputSystemIOS:
            [code appendString:@"#import <CoreImage/CoreImage.h>\n\n"];
            break;
        case FilterCodeGeneratorOutputSystemMac:
            [code appendString:@"#import <QuartzCore/QuartzCore.h>\n\n"];
            break;
    }
    [code appendFormat:@"@interface %@ : NSObject\n\n+ (NSArray *)create;\n\n@end", filterName];
    
    return code;
}

- (void)appendLine:(NSString *)line toString:(NSMutableString *)str {
    [str appendFormat:@"\t\t%@;\n", line];
}

- (NSString *)generateImplementationCode:(NSString *)filterName {
    NSMutableString *code = [NSMutableString new];
    
    [self appendHeader:code];
    
    [code appendFormat:@"#import \"%@.h\"\n\n", filterName];
    
    [code appendFormat:@"@implementation %@\n\n", filterName];
    [code appendFormat:@"\t+ (NSArray *)create {\n"];
    [self appendLine:@"NSMutableArray *filters = [NSMutableArray new]" toString:code];
    [self appendLine:@"CIFilter *currentFilter = nil" toString:code];
    
    for (SCFilter *filter in _filters) {
        [code appendString:@"\n"];
        NSString *line = [NSString stringWithFormat:@"currentFilter = [CIFilter filterWithName:@\"%@\"]", filter.filterDescription.name];
        [self appendLine:line toString:code];
        
        for (SCFilterParameterDescription *parameter in filter.filterDescription.parameters) {
            id value = [filter parameterValueForParameterDescription:parameter];
            NSString *parameterValue = [[[SCFilterParameterConverterManager sharedInstance] converterForParameterDescription:parameter] generateObjCCodeForValue:value];
            
            NSString *parameterLine = [NSString stringWithFormat:@"[currentFilter setValue:%@ forKey:@\"%@\"]", parameterValue, parameter.name];
            [self appendLine:parameterLine toString:code];
        }
        
        [self appendLine:@"[filters addObject:currentFilter]" toString:code];
    }
    
    [self appendLine:@"return filters" toString:code];
    
    [code appendFormat:@"\t}\n\n"];
    [code appendFormat:@"@end\n"];
    
    return code;
}

- (void)generateCode:(NSString *)filterName {
    _generatedHeaderCode = [self generateHeader:filterName];
    _generatedImplementationCode = [self generateImplementationCode:filterName];
}

- (void)saveTo:(NSURL *)url {
    NSURL *headerUrl = [NSURL fileURLWithPath:[[url.path stringByDeletingPathExtension] stringByAppendingPathExtension:@"h"]];
    NSURL *implUrl = [NSURL fileURLWithPath:[[url.path stringByDeletingPathExtension] stringByAppendingPathExtension:@"m"]];
    
    [[NSFileManager defaultManager] removeItemAtURL:headerUrl error:nil];
    [[NSFileManager defaultManager] removeItemAtURL:implUrl error:nil];
    
    [_generatedHeaderCode writeToURL:headerUrl atomically:YES encoding:NSUTF8StringEncoding error:nil];
    [_generatedImplementationCode writeToURL:implUrl atomically:YES encoding:NSUTF8StringEncoding error:nil];
}

@end
